BEGIN TRANSACTION;
CREATE TABLE `joke` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`title`	TEXT NOT NULL,
	`category_id`	INTEGER NOT NULL,
	`content`	TEXT NOT NULL
);
CREATE TABLE `category` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`title`	TEXT NOT NULL,
	`parent_id`	INTEGER
);
COMMIT;
